### ISSUE TITLE
bchkpnt fails on lsbatch/lib/lsb.sig.c at signalJob_() when -p is not specified

### ISSUE THREAD

**Issue by eburgueno** [openlava/openlava#65]
Hello,

I have been trying to integrate [BLCR](http://crd.lbl.gov/departments/computer-science/CLaSS/research/BLCR) with openlava. I created the echkpnt.blcr and erestart.blcr methods (which I've also copied as .default into my $LSF_SERVERDIR), but bchkpnt fails to run when I try to checkpoint a running job:

```
$ bsub -k "/home/user method=blcr" ./test.sh
$ bjobs
JOBID   USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME
370     user  RUN   normal     host    host    ./test.sh     Dec 17 12:40
$ bchkpnt 370
Job <370>: XDR encode/decode error
```

While the error is very non-descriptive, using gdb I managed to trace where the XDR encode fails:

```
(gdb) b xdr_time_t
Breakpoint 1 at 0x440ead: file lib.xdr.c, line 207.
(gdb) run 370
Starting program: /usr/local/src/openlava2/lsbatch/cmd/bchkpnt 370
Detaching after fork from child process 46244.

Breakpoint 1, xdr_time_t (xdrs=0x7fffffffc1d0, t=0x7fffffffe220) at lib.xdr.c:207
207         return(xdr_u_long(xdrs, (unsigned long *)t));
(gdb) bt
#0  xdr_time_t (xdrs=0x7fffffffc1d0, t=0x7fffffffe220) at lib.xdr.c:207
#1  0x000000000040b29b in xdr_signalReq (xdrs=0x7fffffffc1d0, signalReq=0x7fffffffe210, hdr=0x7fffffffc1c0) at lsb.xdr.c:307
#2  0x0000000000440999 in xdr_encodeMsg (xdrs=0x7fffffffc1d0, data=0x7fffffffe210 "\377\377\377\377", hdr=0x7fffffffc1c0, xdr_func=0x40b1f2 <xdr_signalReq>, options=0, auth=0x7fffffffb120) at lib.xdr.c:121
#3  0x0000000000412f0b in signalJob_ (sigValue=-1, jobId=370, period=-1, options=0) at lsb.sig.c:109
#4  0x0000000000412d79 in lsb_chkpntjob (jobId=370, period=-1, options=0) at lsb.sig.c:56
#5  0x0000000000406b0c in signalJobs (jobIds=0x6bbc70, numJobs=1) at cmd.sig.c:311
#6  0x0000000000406aa8 in bsignal (argc=2, argv=0x7fffffffe478) at cmd.sig.c:298
#7  0x0000000000405f8e in main (argc=2, argv=0x7fffffffe478) at bkill.c:38
```

When ran without any options, period is set to -1 and execution fails when xdr_time_t invokes xdr_u_long. I don't know much about C so I can't say if this is expected behaviour or not.

When using -p with any value, period is set to ```<value of -p * 60>```, and bchkpnt finishes correctly:

```
(gdb) b xdr_time_t
Breakpoint 1 at 0x440ead: file lib.xdr.c, line 207.
(gdb) run -p 60 370
Starting program: /usr/local/src/openlava2/lsbatch/cmd/bchkpnt -p 60 370
Detaching after fork from child process 47722.

Breakpoint 1, xdr_time_t (xdrs=0x7fffffffc1c0, t=0x7fffffffe210) at lib.xdr.c:207
207         return(xdr_u_long(xdrs, (unsigned long *)t));
Missing separate debuginfos, use: debuginfo-install tcl-8.5.7-6.el6.x86_64
(gdb) bt
#0  xdr_time_t (xdrs=0x7fffffffc1c0, t=0x7fffffffe210) at lib.xdr.c:207
#1  0x000000000040b29b in xdr_signalReq (xdrs=0x7fffffffc1c0, signalReq=0x7fffffffe200, hdr=0x7fffffffc1b0) at lsb.xdr.c:307
#2  0x0000000000440999 in xdr_encodeMsg (xdrs=0x7fffffffc1c0, data=0x7fffffffe200 "\377\377\377\377", hdr=0x7fffffffc1b0, xdr_func=0x40b1f2 <xdr_signalReq>, options=0, auth=0x7fffffffb110) at lib.xdr.c:121
#3  0x0000000000412f0b in signalJob_ (sigValue=-1, jobId=370, period=3600, options=0) at lsb.sig.c:109
#4  0x0000000000412d79 in lsb_chkpntjob (jobId=370, period=3600, options=0) at lsb.sig.c:56
#5  0x0000000000406b0c in signalJobs (jobIds=0x6bbc70, numJobs=1) at cmd.sig.c:311
#6  0x0000000000406aa8 in bsignal (argc=4, argv=0x7fffffffe468) at cmd.sig.c:298
#7  0x0000000000405f8e in main (argc=4, argv=0x7fffffffe468) at bkill.c:38
(gdb) c
Continuing.
Job <370> is being checkpointed

Program exited normally.
```

Another issue that I've found is that even though using -p seems to work, no checkpointing actually happens. I will probably open another issue for this if I get the time to track down the cause a bit further, but since echkpnt.blcr doesn't seem to be called at all, ever, it's possible the two are related.

**Comment by openlava** [comment]
The xdr problem has been fixed in the latest 3.1.
